apiVersion: apps/v1
kind: Deployment

metadata:
  name: verifier-deployment
  namespace: verifier-ns
  labels:
    app: verifier

spec:
  replicas: 2
  selector:
    matchLabels:
      app: verifier

  template:
    metadata:
      labels:
        app: verifier

    spec:
      containers:
      - name: verifier
        image: ananyaamishraa/verifier
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 256Mi

          limits:
            cpu: 200m
            memory: 512Mi
